/*
 * MIT No Attribution
 *
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Intent {
  /**
   * Description of the intent.
   */
  description?: string;
  /**
   * A list of the slot priorities for the intent. The first element in the array is the top priority, and the last element is the lowest priority. If you don't specify a priority, Amazon Lex does not consider the slot. Slot priorities override slot elimination.
   */
  slotPriorities:
    | []
    | [SlotPriority]
    | [SlotPriority, SlotPriority]
    | [SlotPriority, SlotPriority, SlotPriority]
    | [SlotPriority, SlotPriority, SlotPriority, SlotPriority]
    | [SlotPriority, SlotPriority, SlotPriority, SlotPriority, SlotPriority];
  /**
   * Specifies that Amazon Lex invokes the alias Lambda function for each user input. You can invoke this Lambda function to personalize user interaction.
   */
  dialogCodeHook?: DialogCodeHook;
  /**
   * Specifies that Amazon Lex invokes the alias Lambda function when the intent is ready for fulfillment. You can invoke this function to complete the bot's transaction with the user.
   */
  fulfillmentCodeHook?: FulfillmentCodeHookSettings;
  initialResponseSetting?: InitialResponseSetting;
  /**
   * A list of contexts that must be active for this intent to be considered by Amazon Lex. When an intent has an input context list, Amazon Lex only considers using the intent in an interaction with the user when the specified contexts are included in the active context list for the session. If the contexts are not active, then Amazon Lex will not use the intent. A context can be automatically activated using the outputContexts property or it can be set at runtime. For example, if there are two intents with different input contexts that respond to the same utterances, only the intent with the active context will respond. An intent may have up to 5 input contexts. If an intent has multiple input contexts, all of the contexts must be active to consider the intent.
   */
  inputContexts?:
    | []
    | [InputContext]
    | [InputContext, InputContext]
    | [InputContext, InputContext, InputContext]
    | [InputContext, InputContext, InputContext, InputContext]
    | [InputContext, InputContext, InputContext, InputContext, InputContext];
  /**
   * Provides prompts that Amazon Lex sends to the user to confirm the completion of an intent. If the user answers 'no,' the settings contain a statement that is sent to the user to end the intent.
   */
  intentClosingSetting?: IntentClosingSetting;
  /**
   * Provides prompts that Amazon Lex sends to the user to confirm the completion of an intent. If the user answers 'no,' the settings contain a statement that is sent to the user to end the intent.
   */
  intentConfirmationSetting?: IntentConfirmationSetting;
  /**
   * The name of the intent. Intent names must be unique in the locale that contains the intent and cannot match the name of any built-in intent.
   */
  intentName: string;
  /**
   * Configuration information required to use the AMAZON.KendraSearchIntent intent to connect to an Amazon Kendra index. The AMAZON.KendraSearchIntent intent is called when Amazon Lex can't determine another intent to invoke.
   */
  kendraConfiguration?: KendraConfiguration;
  /**
   * A lists of contexts that the intent activates when it is fulfilled. You can use an output context to indicate the intents that Amazon Lex should consider for the next turn of the conversation with a customer. When you use the outputContextsList property, all of the contexts specified in the list are activated when the intent is fulfilled. You can set up to 10 output contexts. You can also set the number of conversation turns that the context should be active, or the length of time that the context should be active.
   */
  outputContexts?:
    | []
    | [OutputContext]
    | [OutputContext, OutputContext]
    | [OutputContext, OutputContext, OutputContext]
    | [OutputContext, OutputContext, OutputContext, OutputContext]
    | [OutputContext, OutputContext, OutputContext, OutputContext, OutputContext]
    | [OutputContext, OutputContext, OutputContext, OutputContext, OutputContext, OutputContext]
    | [OutputContext, OutputContext, OutputContext, OutputContext, OutputContext, OutputContext, OutputContext]
    | [
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext
      ]
    | [
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext
      ]
    | [
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext,
        OutputContext
      ];
  /**
   * A unique identifier for the built-in intent to base this intent on.
   */
  parentIntentSignature?: string;
  /**
   * Specifies the configuration of the built-in Amazon.QnAIntent. The AMAZON.QnAIntent intent is called when Amazon Lex can't determine another intent to invoke. If you specify this field, you can't specify the kendraConfiguration field.
   */
  qInConnectIntentConfiguration?: QInConnectIntentConfiguration;
  /**
   * An array of strings that a user might say to signal the intent. For example, 'I want a pizza', or 'I want a {PizzaSize} pizza'. In an utterance, slot names are enclosed in curly braces ("{", "}") to indicate where they should be displayed in the utterance shown to the user.
   */
  sampleUtterances?: SampleUtterance[];
}
/**
 * Determines the priority of a slot. A higher priority means that the slot value is more likely to be filled in by Amazon Lex.
 */
export interface SlotPriority {
  /**
   * The priority of the slot. A higher priority means that the slot value is more likely to be filled in by Amazon Lex.
   */
  priority: number;
  /**
   * The name of the slot.
   */
  slotName: string;
  [k: string]: unknown;
}
/**
 * Enables the dialog code hook so that it processes user requests.
 */
export interface DialogCodeHook {
  enabled: boolean;
  [k: string]: unknown;
}
/**
 * Determines if a Lambda function should be invoked for a specific intent.
 */
export interface FulfillmentCodeHookSettings {
  /**
   * Indicates whether a Lambda function should be invoked to fulfill a specific intent.
   */
  enabled: boolean;
  /**
   * Determines whether the fulfillment code hook is used. When active is false, the code hook doesn't run.
   */
  active?: boolean;
  fulfillmentUpdatesSpecification?: FulfillmentUpdatesSpecification;
  postFulfillmentStatusSpecification?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Provides settings for update messages sent to the user for long-running Lambda fulfillment functions. Fulfillment updates can be used only with streaming conversations.
 */
export interface FulfillmentUpdatesSpecification {
  /**
   * Determines whether fulfillment updates are sent to the user. When this field is true, updates are sent. If the active field is set to true, the startResponse, updateResponse, and timeoutInSeconds fields are required.
   */
  active: boolean;
  startResponse?: FulfillmentStartResponseSpecification;
  /**
   * The length of time that the fulfillment Lambda function should run before it times out.
   */
  timeoutInSeconds?: number;
  updateResponse?: FulfillmentUpdateResponseSpecification;
  [k: string]: unknown;
}
/**
 * Provides configuration information for the message sent to users when the fulfillment Lambda functions starts running.
 */
export interface FulfillmentStartResponseSpecification {
  /**
   * The delay between when the Lambda function starts running and the message is placed in the queue.
   */
  delayInSeconds: number;
  /**
   * An array of objects, each of which provides information about a message.
   */
  messageGroups: MessageGroup[];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Provides one or more messages that Amazon Lex should send to the user.
 */
export interface MessageGroup {
  message: Message;
  /**
   * An array of objects, each of which provides information about a message.
   */
  variations?: Message1[];
  [k: string]: unknown;
}
/**
 * The primary message that Amazon Lex should send to the user.
 */
export interface Message {
  customPayload?: CustomPayload;
  imageResponseCard?: ImageResponseCard;
  plainTextMessage?: PlainTextMessage;
  ssmlMessage?: SSMLMessage;
  [k: string]: unknown;
}
/**
 * Provides information about a custom payload.
 */
export interface CustomPayload {
  /**
   * The value of the custom payload.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * Provides information about an image response card.
 */
export interface ImageResponseCard {
  /**
   * The title of the image response card.
   */
  title: string;
  /**
   * A list of buttons that should be displayed on the response card.
   *
   * @minItems 0
   * @maxItems 5
   */
  buttons?:
    | []
    | [Button]
    | [Button, Button]
    | [Button, Button, Button]
    | [Button, Button, Button, Button]
    | [Button, Button, Button, Button, Button];
  /**
   * The URL of an image to display on the response card.
   */
  imageUrl?: string;
  /**
   * The subtitle to display on the response card.
   */
  subtitle?: string;
  [k: string]: unknown;
}
/**
 * Describes a button to use on a response card used to gather slot values from a user.
 */
export interface Button {
  /**
   * The text that should be displayed on the button.
   */
  text: string;
  /**
   * The value returned to Amazon Lex when the user chooses this button. This must be one of the slot values configured for the slot.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * Defines an ASCII text message to send to the user.
 */
export interface PlainTextMessage {
  /**
   * The message to send to the user.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * Defines a Speech Synthesis Markup Language (SSML) prompt.
 */
export interface SSMLMessage {
  /**
   * The SSML text that defines the prompt.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * Message variations to send to the user. When variations are defined, Amazon Lex chooses the primary message or one of the variations to send to the user.
 */
export interface Message1 {
  customPayload?: CustomPayload;
  imageResponseCard?: ImageResponseCard;
  plainTextMessage?: PlainTextMessage;
  ssmlMessage?: SSMLMessage;
  [k: string]: unknown;
}
/**
 * Provides configuration information for messages sent periodically to the user while the fulfillment Lambda function is running.
 */
export interface FulfillmentUpdateResponseSpecification {
  /**
   * The frequency that a message is sent to the user. When the period ends, Amazon Lex chooses a message from the message groups and plays it to the user. If the fulfillment Lambda returns before the first period ends, an update message is not played to the user.
   */
  frequencyInSeconds: number;
  /**
   * 1 - 5 message groups that contain update messages. Amazon Lex chooses one of the messages to play to the user.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Determines whether the user can interrupt an update message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Configuration settings for the response that is sent to the user at the beginning of a conversation, before eliciting slot values.
 */
export interface InitialResponseSetting {
  /**
   * Settings that specify the dialog code hook that is called by Amazon Lex at a step of the conversation.
   */
  codeHook?: CodeHookInvocationSetting;
  /**
   * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
   */
  conditional?: ConditionalSpecification3;
  /**
   * Specifies a list of message groups that Amazon Lex uses to respond the user input.
   */
  initialResponse?: ResponseSpecification5;
  nextStep?: DialogState5;
  [k: string]: unknown;
}
/**
 * Settings that specify the dialog code hook that is called by Amazon Lex at a step of the conversation.
 */
export interface CodeHookInvocationSetting {
  /**
   * Determines whether a dialog code hook is used when the intent is activated.
   */
  active: boolean;
  /**
   * Indicates whether a Lambda function should be invoked for the dialog.
   */
  enableCodeHookInvocation: boolean;
  postCodeHookSpecification: PostDialogCodeHookInvocationSpecification;
  /**
   * A label that indicates the dialog step from which the dialog code hook is happening.
   */
  invocationLabel?: string;
  [k: string]: unknown;
}
/**
 * Contains the responses and actions that Amazon Lex takes after the Lambda function is complete.
 */
export interface PostDialogCodeHookInvocationSpecification {
  failureConditional?: ConditionalSpecification;
  failureNextStep?: DialogState2;
  failureResponse?: ResponseSpecification2;
  successConditional?: ConditionalSpecification1;
  successNextStep?: DialogState3;
  successResponse?: ResponseSpecification3;
  timeoutConditional?: ConditionalSpecification2;
  timeoutNextStep?: DialogState4;
  timeoutResponse?: ResponseSpecification4;
  [k: string]: unknown;
}
/**
 * A list of conditional branches to evaluate after the dialog code hook throws an exception or returns with the State field of the Intent object set to Failed.
 */
export interface ConditionalSpecification {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * A set of actions that Amazon Lex should run if the condition is matched.
 */
export interface ConditionalBranch {
  condition: Condition;
  /**
   * The name of the branch.
   */
  name: string;
  nextStep: DialogState;
  response?: ResponseSpecification;
  [k: string]: unknown;
}
/**
 * Contains the expression to evaluate. If the condition is true, the branch's actions are taken.
 */
export interface Condition {
  /**
   * The expression string that is evaluated.
   */
  expressionString: string;
  [k: string]: unknown;
}
/**
 * The next step in the conversation.
 */
export interface DialogState {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Defines the action that the bot executes at runtime when the conversation reaches this step.
 */
export interface DialogAction {
  /**
   * The action that the bot should execute.
   */
  type:
    | "ElicitIntent"
    | "StartIntent"
    | "ElicitSlot"
    | "EvaluateConditional"
    | "ConfirmIntent"
    | "FulfillIntent"
    | "CloseIntent"
    | "EndConversation";
  /**
   * If the dialog action is ElicitSlot, defines the slot to elicit from the user.
   */
  slotToElicit?: string;
  /**
   * When true the next message for the intent is not used.
   */
  suppressNextMessage?: boolean;
  [k: string]: unknown;
}
/**
 * Override settings to configure the intent state.
 */
export interface IntentOverride {
  /**
   * The name of the intent. Only required when you're switching intents.
   */
  name?: string;
  slots?: {
    [k: string]: SlotValueOverride;
  };
  [k: string]: unknown;
}
/**
 * The slot values that Amazon Lex uses when it sets slot values in a dialog step.
 */
export interface SlotValueOverride {
  /**
   * When the shape value is List, it indicates that the values field contains a list of slot values. When the value is Scalar, it indicates that the value field contains a single value.
   */
  name?: "List" | "Scalar";
  value?: SlotValue;
  /**
   * A list of one or more values that the user provided for the slot. For example, for a slot that elicits pizza toppings, the values might be 'pepperoni' and 'pineapple.'
   */
  values?: SlotValueOverride1[];
}
/**
 * The current value of the slot.
 */
export interface SlotValue {
  /**
   * The value that Amazon Lex determines for the slot. The actual value depends on the setting of the value selection strategy for the bot. You can choose to use the value entered by the user, or you can have Amazon Lex choose the first value in the resolvedValues list.
   */
  interpretedValue?: string;
  [k: string]: unknown;
}
/**
 * The slot values that Amazon Lex uses when it sets slot values in a dialog step.
 */
export interface SlotValueOverride1 {
  /**
   * When the shape value is List, it indicates that the values field contains a list of slot values. When the value is Scalar, it indicates that the value field contains a single value.
   */
  name?: "List" | "Scalar";
  value?: SlotValue;
  /**
   * A list of one or more values that the user provided for the slot. For example, for a slot that elicits pizza toppings, the values might be 'pepperoni' and 'pineapple.'
   */
  values?: SlotValueOverride1[];
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * The default branch that is executed when no other branch has a matching condition.
 */
export interface DefaultConditionalBranch {
  nextStep?: DialogState1;
  response?: ResponseSpecification1;
  [k: string]: unknown;
}
/**
 * The next step in the conversation.
 */
export interface DialogState1 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification1 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Specifies the next step the bot runs after the dialog code hook throws an exception or returns with the State field of the Intent object set to Failed.
 */
export interface DialogState2 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification2 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * A list of conditional branches to evaluate after the dialog code hook finishes successfully.
 */
export interface ConditionalSpecification1 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * Specifics the next step the bot runs after the dialog code hook finishes successfully.
 */
export interface DialogState3 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification3 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * A list of conditional branches to evaluate if the code hook times out.
 */
export interface ConditionalSpecification2 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * Specifies the next step that the bot runs when the code hook times out.
 */
export interface DialogState4 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification4 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
 */
export interface ConditionalSpecification3 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification5 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * The next step in the conversation.
 */
export interface DialogState5 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * A context that must be active for an intent to be selected by Amazon Lex.
 */
export interface InputContext {
  /**
   * The name of the context.
   */
  name: string;
  [k: string]: unknown;
}
/**
 * Provides a statement the Amazon Lex bot conveys to the user when the intent is successfully fulfilled.
 */
export interface IntentClosingSetting {
  /**
   * Specifies whether the closing response is used. Defaults to true if not specified.
   */
  active?: boolean;
  closingResponse?: ResponseSpecification6;
  conditional?: ConditionalSpecification4;
  nextStep?: DialogState6;
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification6 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
 */
export interface ConditionalSpecification4 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * Specifies the next step the bot takes after the closing response.
 */
export interface DialogState6 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Provides a prompt for making sure that the user is ready for the intent to be fulfilled.
 */
export interface IntentConfirmationSetting {
  promptSpecification: PromptSpecification;
  /**
   * Specifies whether the intent's confirmation is sent to the user. When this field is false, confirmation and declination responses aren't sent. If the active field isn't specified, the default is true.
   */
  active?: boolean;
  codeHook?: CodeHookInvocationSetting1;
  confirmationConditional?: ConditionalSpecification5;
  confirmationNextStep?: DialogState7;
  confirmationResponse?: ResponseSpecification7;
  declinationConditional?: ConditionalSpecification6;
  declinationNextStep?: DialogState8;
  declinationResponse?: ResponseSpecification8;
  elicitationCodeHook?: ElicitationCodeHookInvocationSetting;
  failureConditional?: ConditionalSpecification7;
  failureNextStep?: DialogState9;
  failureResponse?: ResponseSpecification9;
  [k: string]: unknown;
}
/**
 * Prompts the user to confirm the intent. This question should have a yes or no answer.Amazon Lex uses this prompt to ensure that the user acknowledges that the intent is ready for fulfillment. For example, with the OrderPizza intent, you might want to confirm that the order is correct before placing it. For other intents, such as intents that simply respond to user questions, you might not need to ask the user for confirmation before providing the information.
 */
export interface PromptSpecification {
  /**
   * The maximum number of times the bot tries to elicit a response from the user using this prompt.
   */
  maxRetries: number;
  /**
   * A collection of messages that Amazon Lex can send to the user. Amazon Lex chooses the actual message to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt a speech prompt from the bot.
   */
  allowInterrupt?: boolean;
  /**
   * Indicates how a message is selected from a message group among retries.
   */
  messageSelectionStrategy?: "Ordered" | "Random";
  /**
   * Specifies the advanced settings on each attempt of the prompt.
   */
  promptAttemptsSpecification?: {
    Initial?: PromptAttemptSpecification;
    Retry1?: PromptAttemptSpecification;
    Retry2?: PromptAttemptSpecification;
    Retry3?: PromptAttemptSpecification;
    Retry4?: PromptAttemptSpecification;
    Retry5?: PromptAttemptSpecification;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Specifies the settings on a prompt attempt.
 */
export interface PromptAttemptSpecification {
  allowedInputTypes: AllowedInputTypes;
  /**
   * Indicates whether the user can interrupt a speech prompt attempt from the bot.
   */
  allowInterrupt?: boolean;
  audioAndDTMFInputSpecification?: AudioAndDTMFInputSpecification;
  textInputSpecification?: TextInputSpecification;
  [k: string]: unknown;
}
/**
 * Indicates the allowed input types of the prompt attempt.
 */
export interface AllowedInputTypes {
  /**
   * Indicates whether audio input is allowed.
   */
  allowAudioInput: boolean;
  /**
   * Indicates whether DTMF input is allowed.
   */
  allowDTMFInput: boolean;
  [k: string]: unknown;
}
/**
 * Specifies the settings on audio and DTMF input.
 */
export interface AudioAndDTMFInputSpecification {
  /**
   * Time for which a bot waits before assuming that the customer isn't going to speak or press a key. This timeout is shared between Audio and DTMF inputs..
   */
  startTimeoutMs: number;
  audioSpecification?: AudioSpecification;
  dtmfSpecification?: DTMFSpecification;
  [k: string]: unknown;
}
/**
 * Specifies the settings on audio input.
 */
export interface AudioSpecification {
  /**
   * Time for which a bot waits after the customer stops speaking to assume the utterance is finished.
   */
  endTimeoutMs: number;
  /**
   * Time for how long Amazon Lex waits before speech input is truncated and the speech is returned to application.
   */
  maxLengthMs: number;
  [k: string]: unknown;
}
/**
 * Specifies the DTMF input specification.
 */
export interface DTMFSpecification {
  /**
   * The DTMF character that clears the accumulated DTMF digits and immediately ends the input.
   */
  deletionCharacter: string;
  /**
   * The DTMF character that immediately ends input. If the user does not press this character, the input ends after the end timeout.
   */
  endCharacter: string;
  /**
   * How long the bot should wait after the last DTMF character input before assuming that the input has concluded.
   */
  endTimeoutMs: number;
  /**
   * The maximum number of DTMF digits allowed in an utterance.
   */
  maxLength: number;
  [k: string]: unknown;
}
/**
 * Specifies the settings on text input.
 */
export interface TextInputSpecification {
  /**
   * TTime for which a bot waits before re-prompting a customer for text input.
   */
  startTimeoutMs: number;
  [k: string]: unknown;
}
/**
 * The CodeHookInvocationSetting object associated with intent's confirmation step. The dialog code hook is triggered based on these invocation settings when the confirmation next step or declination next step or failure next step is InvokeDialogCodeHook.
 */
export interface CodeHookInvocationSetting1 {
  /**
   * Determines whether a dialog code hook is used when the intent is activated.
   */
  active: boolean;
  /**
   * Indicates whether a Lambda function should be invoked for the dialog.
   */
  enableCodeHookInvocation: boolean;
  postCodeHookSpecification: PostDialogCodeHookInvocationSpecification;
  /**
   * A label that indicates the dialog step from which the dialog code hook is happening.
   */
  invocationLabel?: string;
  [k: string]: unknown;
}
/**
 * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
 */
export interface ConditionalSpecification5 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * Specifies the next step that the bot executes when the customer confirms the intent.
 */
export interface DialogState7 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification7 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
 */
export interface ConditionalSpecification6 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * Specifies the next step that the bot executes when the customer declines the intent.
 */
export interface DialogState8 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification8 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * The CodeHookInvocationSetting used when the code hook is invoked during confirmation prompt retries.
 */
export interface ElicitationCodeHookInvocationSetting {
  /**
   * Indicates whether a Lambda function should be invoked for the dialog.
   */
  enableCodeHookInvocation: boolean;
  /**
   * A label that indicates the dialog step from which the dialog code hook is happening.
   */
  invocationLabel?: string;
  [k: string]: unknown;
}
/**
 * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
 */
export interface ConditionalSpecification7 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * The next step to take in the conversation if the confirmation step fails.
 */
export interface DialogState9 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification9 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Provides configuration information for the AMAZON.KendraSearchIntent intent. When you use this intent, Amazon Lex searches the specified Amazon Kendra index and returns documents from the index that match the user's utterance.
 */
export interface KendraConfiguration {
  /**
   * The Amazon Resource Name (ARN) of the Amazon Kendra index that you want the AMAZON.KendraSearchIntent intent to search. The index must be in the same account and Region as the Amazon Lex bot.
   */
  kendraIndex: string;
  /**
   * A query filter that Amazon Lex sends to Amazon Kendra to filter the response from a query. The filter is in the format defined by Amazon Kendra.
   */
  queryFilterString?: string;
  /**
   * Determines whether the AMAZON.KendraSearchIntent intent uses a custom query string to query the Amazon Kendra index.
   */
  queryFilterStringEnabled?: boolean;
  [k: string]: unknown;
}
/**
 * Describes a session context that is activated when an intent is fulfilled.
 */
export interface OutputContext {
  /**
   * The name of the context.
   */
  name: string;
  /**
   * The amount of time, in seconds, that the output context should remain active. The time is figured from the first time the context is sent to the user.
   */
  timeToLiveInSeconds: number;
  /**
   * The number of conversation turns that the output context should remain active. The number of turns is counted from the first time that the context is sent to the user.
   */
  turnsToLive: number;
  [k: string]: unknown;
}
/**
 * The configuration details of the Qinconnect intent.
 */
export interface QInConnectIntentConfiguration {
  qInConnectAssistantConfiguration?: QInConnectAssistantConfiguration;
  [k: string]: unknown;
}
/**
 * The Qinconnect assistant configuration details of the Qinconnect intent
 */
export interface QInConnectAssistantConfiguration {
  /**
   * The assistant Arn details of the Qinconnect assistant configuration.
   */
  assistantArn: string;
  [k: string]: unknown;
}
/**
 * A sample utterance that invokes an intent or respond to a slot elicitation prompt.
 */
export interface SampleUtterance {
  /**
   * The sample utterance that Amazon Lex uses to build its machine-learning model to recognize intents.
   */
  utterance: string;
  [k: string]: unknown;
}
