/*
 * MIT No Attribution
 *
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SlotExportDefinition {
  /**
   * The unique identifier for the slot. The identifier is only unique within the bot that contains the slot.
   */
  identifier?: string;
  /**
   * A description of the slot. Use this to help identify the slot in lists.
   */
  description?: string;
  /**
   * Indicates whether the slot returns multiple values in one response. Multi-value slots are only available in the en-US locale. If you set this value to true in any other locale, Amazon Lex throws a ValidationException. If the multipleValuesSetting is not set, the default value is false.
   */
  multipleValuesSetting?: MultipleValuesSetting;
  /**
   * Determines how slot values are used in Amazon CloudWatch logs. If the value of the obfuscationSetting parameter is DefaultObfuscation, slot values are obfuscated in the log output. If the value is None, the actual value is present in the log output. The default is to obfuscate values in the CloudWatch logs.
   */
  obfuscationSetting?: ObfuscationSetting;
  /**
   * The name of the slot. Slot names must be unique within the bot that contains the slot.
   */
  slotName: string;
  /**
   * The unique identifier for the slot type associated with this slot. The slot type determines the values that can be entered into the slot.
   */
  slotTypeName?: string;
  subSlotSetting?: SubSlotSetting;
  valueElicitationSetting: SlotValueElicitationSetting;
}
/**
 * Indicates whether a slot can return multiple values.
 */
export interface MultipleValuesSetting {
  /**
   * Indicates whether a slot can return multiple values. When true, the slot may return more than one value in a response. When false, the slot returns only a single value. Multi-value slots are only available in the en-US locale. If you set this value to true in any other locale, Amazon Lex throws a ValidationException.
   */
  allowMultipleValues?: boolean;
}
/**
 * Determines whether Amazon Lex obscures slot values in conversation logs.
 */
export interface ObfuscationSetting {
  /**
   * Value that determines whether Amazon Lex obscures slot values in conversation logs. The default is to obscure the values.
   */
  obfuscationSettingType: "DefaultObfuscation" | "None";
}
/**
 * Specifications for the constituent sub slots and the expression for the composite slot.
 */
export interface SubSlotSetting {
  /**
   * The expression text for defining the constituent sub slots in the composite slot using logical AND and OR operators.
   */
  expression?: string;
  slotSpecifications?: {
    [k: string]: Specifications;
  };
}
/**
 * Subslot specifications.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^([0-9a-zA-Z][_-]?){1,100}$".
 */
export interface Specifications {
  /**
   * The unique identifier assigned to the slot type.
   */
  slotTypeName: string;
  valueElicitationSetting: SubSlotValueElicitationSetting;
}
/**
 * Specifies the elicitation setting details for constituent sub slots of a composite slot.
 */
export interface SubSlotValueElicitationSetting {
  promptSpecification: PromptSpecification;
  defaultValueSpecification?: SlotDefaultValueSpecification;
  /**
   * If you know a specific pattern that users might respond to an Amazon Lex request for a sub slot value, you can provide those utterances to improve accuracy. This is optional. In most cases Amazon Lex is capable of understanding user utterances. This is similar to SampleUtterances for slots.
   */
  sampleUtterances?: SampleUtterance[];
  waitAndContinueSpecification?: WaitAndContinueSpecification;
}
/**
 * Specifies a list of message groups that Amazon Lex sends to a user to elicit a response.
 */
export interface PromptSpecification {
  /**
   * The maximum number of times the bot tries to elicit a response from the user using this prompt.
   */
  maxRetries: number;
  /**
   * A collection of messages that Amazon Lex can send to the user. Amazon Lex chooses the actual message to send at runtime.
   */
  messageGroups: MessageGroup[];
  /**
   * Indicates whether the user can interrupt a speech prompt from the bot.
   */
  allowInterrupt?: boolean;
  /**
   * Indicates how a message is selected from a message group among retries.
   */
  messageSelectionStrategy?: "Ordered" | "Random";
  /**
   * Specifies the advanced settings on each attempt of the prompt.
   */
  promptAttemptsSpecification?: {
    Initial?: PromptAttemptSpecification;
    Retry1?: PromptAttemptSpecification;
    Retry2?: PromptAttemptSpecification;
    Retry3?: PromptAttemptSpecification;
    Retry4?: PromptAttemptSpecification;
    Retry5?: PromptAttemptSpecification;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Provides one or more messages that Amazon Lex should send to the user.
 */
export interface MessageGroup {
  message: Message;
  /**
   * An array of objects, each of which provides information about a message.
   */
  variations?: Message1[];
  [k: string]: unknown;
}
/**
 * The primary message that Amazon Lex should send to the user.
 */
export interface Message {
  customPayload?: CustomPayload;
  imageResponseCard?: ImageResponseCard;
  plainTextMessage?: PlainTextMessage;
  ssmlMessage?: SSMLMessage;
  [k: string]: unknown;
}
/**
 * Provides information about a custom payload.
 */
export interface CustomPayload {
  /**
   * The value of the custom payload.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * Provides information about an image response card.
 */
export interface ImageResponseCard {
  /**
   * The title of the image response card.
   */
  title: string;
  /**
   * A list of buttons that should be displayed on the response card.
   *
   * @minItems 0
   * @maxItems 5
   */
  buttons?:
    | []
    | [Button]
    | [Button, Button]
    | [Button, Button, Button]
    | [Button, Button, Button, Button]
    | [Button, Button, Button, Button, Button];
  /**
   * The URL of an image to display on the response card.
   */
  imageUrl?: string;
  /**
   * The subtitle to display on the response card.
   */
  subtitle?: string;
  [k: string]: unknown;
}
/**
 * Describes a button to use on a response card used to gather slot values from a user.
 */
export interface Button {
  /**
   * The text that should be displayed on the button.
   */
  text: string;
  /**
   * The value returned to Amazon Lex when the user chooses this button. This must be one of the slot values configured for the slot.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * Defines an ASCII text message to send to the user.
 */
export interface PlainTextMessage {
  /**
   * The message to send to the user.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * Defines a Speech Synthesis Markup Language (SSML) prompt.
 */
export interface SSMLMessage {
  /**
   * The SSML text that defines the prompt.
   */
  value: string;
  [k: string]: unknown;
}
/**
 * Message variations to send to the user. When variations are defined, Amazon Lex chooses the primary message or one of the variations to send to the user.
 */
export interface Message1 {
  customPayload?: CustomPayload;
  imageResponseCard?: ImageResponseCard;
  plainTextMessage?: PlainTextMessage;
  ssmlMessage?: SSMLMessage;
  [k: string]: unknown;
}
/**
 * Specifies the settings on a prompt attempt.
 */
export interface PromptAttemptSpecification {
  allowedInputTypes: AllowedInputTypes;
  /**
   * Indicates whether the user can interrupt a speech prompt attempt from the bot.
   */
  allowInterrupt?: boolean;
  audioAndDTMFInputSpecification?: AudioAndDTMFInputSpecification;
  textInputSpecification?: TextInputSpecification;
  [k: string]: unknown;
}
/**
 * Indicates the allowed input types of the prompt attempt.
 */
export interface AllowedInputTypes {
  /**
   * Indicates whether audio input is allowed.
   */
  allowAudioInput: boolean;
  /**
   * Indicates whether DTMF input is allowed.
   */
  allowDTMFInput: boolean;
  [k: string]: unknown;
}
/**
 * Specifies the settings on audio and DTMF input.
 */
export interface AudioAndDTMFInputSpecification {
  /**
   * Time for which a bot waits before assuming that the customer isn't going to speak or press a key. This timeout is shared between Audio and DTMF inputs..
   */
  startTimeoutMs: number;
  audioSpecification?: AudioSpecification;
  dtmfSpecification?: DTMFSpecification;
  [k: string]: unknown;
}
/**
 * Specifies the settings on audio input.
 */
export interface AudioSpecification {
  /**
   * Time (in milliseconds) that Lex waits after the customer stops speaking before assuming the utterance is finished.
   */
  endTimeoutMs: number;
  /**
   * Maximum time (in milliseconds) Lex waits before truncating speech input and returning it to the application.
   */
  maxLengthMs: number;
}
/**
 * Specifies the DTMF input specification.
 */
export interface DTMFSpecification {
  /**
   * The DTMF character that clears accumulated digits and ends the input.
   */
  deletionCharacter: string;
  /**
   * The DTMF character that immediately ends the input.
   */
  endCharacter: string;
  /**
   * How long the bot should wait after the last DTMF character before assuming the input has concluded (in milliseconds).
   */
  endTimeoutMs: number;
  /**
   * The maximum number of DTMF digits allowed in the utterance.
   */
  maxLength: number;
}
/**
 * Specifies the settings on text input.
 */
export interface TextInputSpecification {
  /**
   * TTime for which a bot waits before re-prompting a customer for text input.
   */
  startTimeoutMs: number;
  [k: string]: unknown;
}
/**
 * Defines a list of values that Amazon Lex should use as the default value for a slot.
 */
export interface SlotDefaultValueSpecification {
  /**
   * A list of default values. Amazon Lex chooses the default value to use in the order that they are presented in the list.
   *
   * @minItems 0
   * @maxItems 10
   */
  defaultValueList:
    | []
    | [SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue, SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue]
    | [
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue
      ]
    | [
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue
      ]
    | [
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue
      ]
    | [
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue
      ];
  [k: string]: unknown;
}
/**
 * Specifies the default value to use when a user doesn't provide a value for a slot.
 */
export interface SlotDefaultValue {
  /**
   * The default value to use when a user doesn't provide a value for a slot.
   */
  defaultValue: string;
  [k: string]: unknown;
}
/**
 * A sample utterance that invokes an intent or respond to a slot elicitation prompt.
 */
export interface SampleUtterance {
  /**
   * The sample utterance that Amazon Lex uses to build its machine-learning model to recognize intents.
   */
  utterance: string;
  [k: string]: unknown;
}
/**
 * Specifies the prompts that Amazon Lex uses while a bot is waiting for customer input.
 */
export interface WaitAndContinueSpecification {
  continueResponse: ResponseSpecification;
  waitingResponse: ResponseSpecification1;
  /**
   * Specifies whether the bot will wait for a user to respond. When this field is false, wait and continue responses for a slot aren't used. If the active field isn't specified, the default is true.
   */
  active?: boolean;
  stillWaitingResponse?: StillWaitingResponseSpecification;
  [k: string]: unknown;
}
/**
 * The response that Amazon Lex sends to indicate that the bot is ready to continue the conversation.
 */
export interface ResponseSpecification {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * The response that Amazon Lex sends to indicate that the bot is waiting for the conversation to continue.
 */
export interface ResponseSpecification1 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * A response that Amazon Lex sends periodically to the user to indicate that the bot is still waiting for input from the user.
 */
export interface StillWaitingResponseSpecification {
  /**
   * How often a message should be sent to the user.
   */
  frequencyInSeconds: number;
  /**
   * One or more message groups, each containing one or more messages, that define the prompts that Amazon Lex sends to the user.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * If Amazon Lex waits longer than this length of time for a response, it will stop sending messages.
   */
  timeoutInSeconds: number;
  /**
   * Indicates that the user can interrupt the response by speaking while the message is being played.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Specifies prompts that Amazon Lex sends to the user to elicit a response that provides the value for the slot.
 */
export interface SlotValueElicitationSetting {
  /**
   * Specifies whether the slot is required or optional.
   */
  slotConstraint: "Optional" | "Required";
  /**
   * A list of default values for a slot. Default values are used when Amazon Lex hasn't determined a value for a slot. You can specify default values from context variables, session attributes, and defined values.
   */
  defaultValueSpecification?: SlotDefaultValueSpecification1;
  promptSpecification?: PromptSpecification1;
  /**
   * If you know a specific pattern that users might respond to an Amazon Lex request for a slot value, you can provide those utterances to improve accuracy. This is optional. In most cases, Amazon Lex is capable of understanding user utterances.
   */
  sampleUtterances?: SampleUtterance[];
  slotCaptureSetting?: SlotCaptureSetting;
  slotResolutionSetting?: SlotResolutionSetting;
  /**
   * Specifies the prompts that Amazon Lex uses while a bot is waiting for customer input.
   */
  waitAndContinueSpecification?: WaitAndContinueSpecification1;
}
/**
 * Defines a list of values that Amazon Lex should use as the default value for a slot.
 */
export interface SlotDefaultValueSpecification1 {
  /**
   * A list of default values. Amazon Lex chooses the default value to use in the order that they are presented in the list.
   *
   * @minItems 0
   * @maxItems 10
   */
  defaultValueList:
    | []
    | [SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue, SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue]
    | [SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue, SlotDefaultValue]
    | [
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue
      ]
    | [
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue
      ]
    | [
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue
      ]
    | [
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue,
        SlotDefaultValue
      ];
  [k: string]: unknown;
}
/**
 * The prompt that Amazon Lex uses to elicit the slot value from the user.
 */
export interface PromptSpecification1 {
  /**
   * The maximum number of times the bot tries to elicit a response from the user using this prompt.
   */
  maxRetries: number;
  /**
   * A collection of messages that Amazon Lex can send to the user. Amazon Lex chooses the actual message to send at runtime.
   */
  messageGroups: MessageGroup[];
  /**
   * Indicates whether the user can interrupt a speech prompt from the bot.
   */
  allowInterrupt?: boolean;
  /**
   * Indicates how a message is selected from a message group among retries.
   */
  messageSelectionStrategy?: "Ordered" | "Random";
  /**
   * Specifies the advanced settings on each attempt of the prompt.
   */
  promptAttemptsSpecification?: {
    Initial?: PromptAttemptSpecification;
    Retry1?: PromptAttemptSpecification;
    Retry2?: PromptAttemptSpecification;
    Retry3?: PromptAttemptSpecification;
    Retry4?: PromptAttemptSpecification;
    Retry5?: PromptAttemptSpecification;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Specifies the settings that Amazon Lex uses when a slot value is successfully entered by a user.
 */
export interface SlotCaptureSetting {
  /**
   * A list of conditional branches to evaluate after the slot value is captured.
   */
  captureConditional?: ConditionalSpecification;
  captureNextStep?: DialogState2;
  /**
   * Specifies a list of message groups that Amazon Lex uses to respond the user input.
   */
  captureResponse?: ResponseSpecification4;
  /**
   * Code hook called after Amazon Lex successfully captures a slot value.
   */
  codeHook?: DialogCodeHookInvocationSetting;
  elicitationCodeHook?: ElicitationCodeHookInvocationSetting;
  /**
   * A list of conditional branches to evaluate when the slot value isn't captured.
   */
  failureConditional?: ConditionalSpecification;
  failureNextStep?: DialogState6;
  /**
   * Specifies a list of message groups that Amazon Lex uses to respond the user input.
   */
  failureResponse?: ResponseSpecification4;
}
/**
 * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
 */
export interface ConditionalSpecification {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * A set of actions that Amazon Lex should run if the condition is matched.
 */
export interface ConditionalBranch {
  condition: Condition;
  /**
   * The name of the branch.
   */
  name: string;
  nextStep: DialogState;
  response?: ResponseSpecification2;
}
/**
 * Contains the expression to evaluate. If the condition is true, the branch's actions are taken.
 */
export interface Condition {
  /**
   * The expression string that is evaluated.
   */
  expressionString: string;
  [k: string]: unknown;
}
/**
 * The next step in the conversation.
 */
export interface DialogState {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Defines the action that the bot executes at runtime when the conversation reaches this step.
 */
export interface DialogAction {
  /**
   * The action that the bot should execute.
   */
  type:
    | "ElicitIntent"
    | "StartIntent"
    | "ElicitSlot"
    | "EvaluateConditional"
    | "InvokeDialogCodeHook"
    | "ConfirmIntent"
    | "FulfillIntent"
    | "CloseIntent"
    | "EndConversation";
  /**
   * If the dialog action is ElicitSlot, defines the slot to elicit from the user.
   */
  slotToElicit?: string;
  /**
   * When true the next message for the intent is not used.
   */
  suppressNextMessage?: boolean;
  [k: string]: unknown;
}
/**
 * Override settings to configure the intent state.
 */
export interface IntentOverride {
  /**
   * The name of the intent. Only required when you're switching intents.
   */
  name?: string;
  slots?: {
    [k: string]: SlotValueOverride;
  };
  [k: string]: unknown;
}
/**
 * The slot values that Amazon Lex uses when it sets slot values in a dialog step.
 */
export interface SlotValueOverride {
  /**
   * When the shape value is List, it indicates that the values field contains a list of slot values. When the value is Scalar, it indicates that the value field contains a single value.
   */
  name?: "List" | "Scalar";
  value?: SlotValue;
  /**
   * A list of one or more values that the user provided for the slot. For example, for a slot that elicits pizza toppings, the values might be 'pepperoni' and 'pineapple.'
   */
  values?: SlotValueOverride1[];
}
/**
 * The current value of the slot.
 */
export interface SlotValue {
  /**
   * The value that Amazon Lex determines for the slot. The actual value depends on the setting of the value selection strategy for the bot. You can choose to use the value entered by the user, or you can have Amazon Lex choose the first value in the resolvedValues list.
   */
  interpretedValue?: string;
  [k: string]: unknown;
}
/**
 * The slot values that Amazon Lex uses when it sets slot values in a dialog step.
 */
export interface SlotValueOverride1 {
  /**
   * When the shape value is List, it indicates that the values field contains a list of slot values. When the value is Scalar, it indicates that the value field contains a single value.
   */
  name?: "List" | "Scalar";
  value?: SlotValue;
  /**
   * A list of one or more values that the user provided for the slot. For example, for a slot that elicits pizza toppings, the values might be 'pepperoni' and 'pineapple.'
   */
  values?: SlotValueOverride1[];
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification2 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * The default branch that is executed when no other branch has a matching condition.
 */
export interface DefaultConditionalBranch {
  nextStep?: DialogState1;
  response?: ResponseSpecification3;
  [k: string]: unknown;
}
/**
 * The next step in the conversation if this branch is executed.
 */
export interface DialogState1 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond to the user.
 */
export interface ResponseSpecification3 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Specifies the next step that the bot runs when the slot value is captured before the code hook times out.
 */
export interface DialogState2 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification4 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Settings that specify the dialog code hook that is called by Amazon Lex at a step of the conversation.
 */
export interface DialogCodeHookInvocationSetting {
  /**
   * Determines whether a dialog code hook is used when the intent is activated.
   */
  active: boolean;
  /**
   * Indicates whether a Lambda function should be invoked for the dialog.
   */
  enableCodeHookInvocation: boolean;
  postCodeHookSpecification: PostDialogCodeHookInvocationSpecification;
  /**
   * A label that indicates the dialog step from which the dialog code hook is happening.
   */
  invocationLabel?: string;
  [k: string]: unknown;
}
/**
 * Contains the responses and actions that Amazon Lex takes after the Lambda function is complete.
 */
export interface PostDialogCodeHookInvocationSpecification {
  /**
   * A list of conditional branches to evaluate after the dialog code hook throws an exception or returns with the State field of the Intent object set to Failed.
   */
  failureConditional?: ConditionalSpecification;
  failureNextStep?: DialogState3;
  failureResponse?: ResponseSpecification5;
  successConditional?: ConditionalSpecification1;
  successNextStep?: DialogState4;
  successResponse?: ResponseSpecification6;
  timeoutConditional?: ConditionalSpecification2;
  timeoutNextStep?: DialogState5;
  timeoutResponse?: ResponseSpecification7;
  [k: string]: unknown;
}
/**
 * Specifies the next step the bot runs after the dialog code hook throws an exception or returns with the State field of the Intent object set to Failed.
 */
export interface DialogState3 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification5 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
 */
export interface ConditionalSpecification1 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * Specifics the next step the bot runs after the dialog code hook finishes successfully.
 */
export interface DialogState4 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification6 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Provides a list of conditional branches. Branches are evaluated in the order that they are entered in the list. The first branch with a condition that evaluates to true is executed. The last branch in the list is the default branch. The default branch should not have any condition expression. The default branch is executed if no other branch has a matching condition.
 */
export interface ConditionalSpecification2 {
  /**
   * Determines whether a conditional branch is active. When active is false, the conditions are not evaluated..
   */
  active: boolean;
  /**
   * A list of conditional branches. A conditional branch is made up of a condition, a response and a next step. The response and next step are executed when the condition is true.
   *
   * @minItems 1
   * @maxItems 4
   */
  conditionalBranches:
    | [ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch]
    | [ConditionalBranch, ConditionalBranch, ConditionalBranch, ConditionalBranch];
  defaultBranch: DefaultConditionalBranch;
  [k: string]: unknown;
}
/**
 * Specifies the next step that the bot runs when the code hook times out.
 */
export interface DialogState5 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies a list of message groups that Amazon Lex uses to respond the user input.
 */
export interface ResponseSpecification7 {
  /**
   * A collection of responses that Amazon Lex can send to the user. Amazon Lex chooses the actual response to send at runtime.
   *
   * @minItems 1
   * @maxItems 5
   */
  messageGroups:
    | [MessageGroup]
    | [MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup]
    | [MessageGroup, MessageGroup, MessageGroup, MessageGroup, MessageGroup];
  /**
   * Indicates whether the user can interrupt an in-progress message while it is playing.
   */
  allowInterrupt?: boolean;
  [k: string]: unknown;
}
/**
 * Code hook called when Amazon Lex doesn't capture a slot value.
 */
export interface ElicitationCodeHookInvocationSetting {
  /**
   * Indicates whether a Lambda function should be invoked for the dialog.
   */
  enableCodeHookInvocation: boolean;
  /**
   * A label that indicates the dialog step from which the dialog code hook is happening.
   */
  invocationLabel?: string;
  [k: string]: unknown;
}
/**
 * Specifies the next step that the bot runs when the slot value code is not recognized.
 */
export interface DialogState6 {
  dialogAction?: DialogAction;
  intent?: IntentOverride;
  /**
   * Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex and a client application.
   */
  sessionAttributes?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
/**
 * Specifies the settings that Amazon Lex uses when a slot value is successfully entered by a user.
 */
export interface SlotResolutionSetting {
  /**
   * Specifies whether assisted slot resolution is turned on for the slot or not. If the value is EnhancedFallback, assisted slot resolution is activated when Amazon Lex defaults to the AMAZON.FallbackIntent. If the value is Default, assisted slot resolution is turned off.
   */
  slotResolutionStrategy: "EnhancedFallback" | "Default";
  [k: string]: unknown;
}
/**
 * Specifies the prompts that Amazon Lex uses while a bot is waiting for customer input
 */
export interface WaitAndContinueSpecification1 {
  continueResponse: ResponseSpecification;
  waitingResponse: ResponseSpecification1;
  /**
   * Specifies whether the bot will wait for a user to respond. When this field is false, wait and continue responses for a slot aren't used. If the active field isn't specified, the default is true.
   */
  active?: boolean;
  stillWaitingResponse?: StillWaitingResponseSpecification;
  [k: string]: unknown;
}
